name: Package flags and upload to S3

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      brightly-version:
        description: 'The version of the brightly code to use. This can be any valid git tag, branch, or commit hash from https://github.com/brightlyorg/brightly'
        type: string
        required: false
        default: ''

concurrency:
  group: brightly
  cancel-in-progress: false

env:
  BRIGHTLY_S3_BUCKET: ${{ vars.AWS_S3_BUCKET }}
  BRIGHTLY_ENDPOINT: ${{ vars.BRIGHTLY_ENDPOINT }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ vars.AWS_REGION }}

    - name: Set up Go
      uses: actions/setup-go@v5 # see https://github.com/actions/setup-go/tags for latest version
      with:
        go-version: '1.22.2'

    - name: Build go binary
      run: go install github.com/brightlyorg/brightly/cmd/brightly@${{ inputs.brightly-version || vars.BRIGHTLY_VERSION }}

    - name: Process flag changes and upsert to S3
      run: brightly